BetaHuhn/gh-repo-automation2:
  - source: test.txt
    dest: test.txt
BetaHuhn/gh-repo-automation2@test1:
  - source: test.txt
    dest: test.txt
BetaHuhn/gh-repo-automation2@error:
  - source: test.txt
    dest: test.txt