name: Dependabot PR CI
on:
  pull_request:
jobs:
  auto-merge:
    name: Merge and label minor/patch updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          token: ${{ secrets.GH_PAT }}