name: Workflow Sync
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      enableSSH:
        description: 'Enable the SSH action (set to true to enable it)'     
        required: false
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.2.0
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          SKIP_PR: true
      - name: Create SSH Session
        if: ${{ github.event.inputs.enableSSH == 'true' }}
        uses: ryanchapman/gha-ssh@v1
        timeout-minutes: 5
        with:
          authorized_github_users: 'BetaHuhn'