name: Workflow Sync
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/action-github-file-sync@feat/overwrite-existing-pr
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          OVERWRITE_EXISTING_PR: false