name: Workflow Sync
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
      - name: Run GitHub File Sync
        uses: xanjohns/repo-file-sync-action@fork-feature
        with:
          GH_PAT: ${{ secrets.GH_PAT }}