name: Upload to DO Spaces
on:
  workflow_dispatch:
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - uses: BetaHuhn/do-spaces-action@develop
        with:
          access_key: ${{ secrets.SPACE_ACCESS_KEY}}
          secret_key: ${{ secrets.SPACE_SECRET_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: src
          out_dir: test/gh-repo-automation
          versioning: true